---

# Variables here are applicable to all host groups
backup_dir: "{{ deploy_dir }}/backup"
package_dir: "{{ deploy_dir }}/package"

# Local
ansible_log_dir: "{{ playbook_dir }}/log"
downloads_dir: "{{ playbook_dir }}/downloads"
conf_dir: "{{ playbook_dir }}/conf"

# Random shifts for retrying failed ops like downloading
retry_stagger: 5

